# Generated by Django 4.1.7 on 2023-04-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rgb', models.CharField(max_length=100)),
                ('is_trans', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Minifig',
            fields=[
                ('fig_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('num_parts', models.IntegerField()),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=250)),
                ('part_cat_id', models.IntegerField()),
                ('part_material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part_Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('num_parts', models.IntegerField()),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SetPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('is_spare', models.BooleanField()),
                ('part_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.part')),
                ('set_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.set')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='theme_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.theme'),
        ),
        migrations.CreateModel(
            name='Inventory_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.inventories')),
                ('set_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.set')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_spare', models.BooleanField()),
                ('img_url', models.CharField(max_length=200)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.color')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.inventories')),
                ('part_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.part')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_MiniFig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('fig_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.minifig')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.inventories')),
            ],
        ),
        migrations.AddField(
            model_name='inventories',
            name='set_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.set'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('set', models.ManyToManyField(to='main_app.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
