# Generated by Django 4.1.7 on 2023-04-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='is_trans',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='minifig',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
