# Generated by Django 4.1.7 on 2023-03-30 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=100)),
                ('part_cat_id', models.IntegerField()),
                ('part_material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('design_id', models.IntegerField()),
                ('part_name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200)),
                ('set_count', models.IntegerField()),
                ('part_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.part')),
                ('set_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.set')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='part',
            field=models.ManyToManyField(through='main_app.SetPart', to='main_app.part'),
        ),
    ]
