# Generated by Django 4.1.7 on 2023-03-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='last_modified_dt',
        ),
        migrations.RemoveField(
            model_name='set',
            name='num_minifigs',
        ),
        migrations.RemoveField(
            model_name='set',
            name='set_url',
        ),
    ]
