# Generated by Django 4.1.7 on 2023-04-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_color_is_trans_alter_minifig_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='set',
        ),
        migrations.RemoveField(
            model_name='inventories',
            name='set_num',
        ),
        migrations.AddField(
            model_name='collection',
            name='set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.set'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventories',
            name='set_num',
            field=models.ManyToManyField(through='main_app.Inventory_Set', to='main_app.set'),
        ),
    ]
