# Generated by Django 4.1.7 on 2023-03-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_part_setpart_set_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpart',
            name='part_name',
            field=models.CharField(max_length=200),
        ),
    ]
