# Generated by Django 4.1.7 on 2023-04-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_collection_last_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_spare', models.BooleanField()),
                ('img_url', models.CharField(max_length=200)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.collection')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.color')),
                ('part_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.part')),
            ],
        ),
    ]
