# Generated by Django 4.1.7 on 2023-03-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='set',
            field=models.ManyToManyField(to='main_app.set'),
        ),
    ]
