# Generated by Django 4.1.7 on 2023-04-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_collection_set_remove_inventories_set_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventories',
            name='set_num',
        ),
    ]
