# Generated by Django 4.1.7 on 2023-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_setpart_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpart',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='setpart',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
