# Generated by Django 4.1.7 on 2023-03-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_collection_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='user_id',
        ),
    ]
