# Generated by Django 4.1.7 on 2023-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_setpart_category_alter_setpart_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpart',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
    ]
