# Generated by Django 4.1.7 on 2023-04-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_inventory_set_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='set_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.set'),
            preserve_default=False,
        ),
    ]
