# Generated by Django 4.1.7 on 2023-03-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_setpart_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=200),
        ),
    ]
