# Generated by Django 4.1.7 on 2023-04-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_inventories_set_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='set',
        ),
        migrations.AddField(
            model_name='set',
            name='collection',
            field=models.ManyToManyField(to='main_app.collection'),
        ),
    ]
