# Generated by Django 4.1.7 on 2023-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_collection_set_set_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='inventory',
            field=models.ManyToManyField(through='main_app.Inventory_Set', to='main_app.inventories'),
        ),
    ]
