# Generated by Django 4.1.7 on 2023-03-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_delete_user_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setpart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='setpart',
            name='design_id',
        ),
        migrations.RemoveField(
            model_name='setpart',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='setpart',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='setpart',
            name='set_count',
        ),
        migrations.AddField(
            model_name='setpart',
            name='is_spare',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setpart',
            name='color',
            field=models.IntegerField(),
        ),
    ]
