# Generated by Django 4.1.7 on 2023-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_set_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventories',
            name='set_num',
        ),
        migrations.AddField(
            model_name='inventories',
            name='set_num',
            field=models.ManyToManyField(through='main_app.Inventory_Set', to='main_app.set'),
        ),
    ]
